# Generated by Django 4.1.7 on 2023-05-07 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('activeUsers', models.PositiveIntegerField(null=True)),
                ('screen', models.BooleanField(default=True)),
                ('handheld', models.BooleanField(default=True)),
                ('size', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'platform',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, null=True, unique=True)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('email', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(default='NB', max_length=2)),
                ('favouriteGenre', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'player',
                'ordering': ['-username'],
            },
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('releaseYear', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('company', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames_api.platform')),
            ],
            options={
                'db_table': 'videogame',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hoursPlayed', models.SmallIntegerField(default=0)),
                ('hasSaveFile', models.BooleanField(default=False)),
                ('gamename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames_api.videogame')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames_api.player')),
            ],
            options={
                'db_table': 'playergame',
                'ordering': ['-username'],
            },
        ),
    ]
