# Generated by Django 4.1.7 on 2023-05-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames_api.platform', to_field='name'),
        ),
    ]
