# Generated by Django 4.1.7 on 2023-05-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0002_alter_videogame_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videogame',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
