# Generated by Django 4.1.7 on 2023-05-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0004_alter_platform_name_alter_player_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogames_api.platform', to_field='name'),
        ),
    ]
