# Generated by Django 4.1.7 on 2023-05-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_api', '0006_alter_videogame_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
